# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.


# Theme Settings
minimal_mistakes_skin    : "air"

# Site Settings
locale                   : "en-US"
title                    : "Gabriel Kenji G. Shimanuki"
title_separator          : "-"
subtitle                 : "Personal webpage"
name                     : "Gabriel Kenji G. Shimanuki"
description              : "Gabriel Kenji G. Shimanuki description..."
url                      : "https://gabrielshimanuki.github.io"
baseurl                  : "" 
repository               : "GabrielShimanuki/gabrielshimanuki.github.io"
teaser                   : "/assets/images/GS_profile_crop_2023.JPEG" 
masthead_title           : "" 
words_per_minute         : 200

comments:
  provider               : false

# Social Sharing
twitter:
  username               : gabrielkenji_13

# Social Profiles
social:
  type                   : Person
  name                   : Gabriel Kenji
  links: 
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/gabriel-kenji/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/GabrielShimanuki"
    # - label: "Google Scholar"
    #   icon: "fas fa-fw fa-graduation-cap"
    #   url: "https://scholar.google.com/citations?user=B647vnMAAAAJ&hl=en"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-5412-8910"

# Analytics
analytics:
  provider               : false 

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/gabriel-kenji/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/GabrielShimanuki"
    # - label: "Google Scholar"
    #   icon: "fas fa-fw fa-graduation-cap"
    #   url: "https://scholar.google.com/citations?user=B647vnMAAAAJ&hl=en"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-5412-8910"


# Site Author
author:
  name             : "Gabriel Kenji G. Shimanuki"
  avatar           : "/assets/images/GS_profile_crop_2023.JPEG"
  # bio              : "Researcher in Computer Engineering focusing on machine learning applied to autonomous vehicles safety - <strong>[USP](https://www5.usp.br/#english)</strong> <br/> gabrielshimanuki [at] usp [dot] br"
  # bio              : "Researcher in Electrical/Computer Engineering, specializing in machine learning and simulation for enhancing autonomous vehicle safety - <strong>[Safety Analysis Group (GAS)](https://www2.pcs.usp.br/~gas/) at <strong>[University of Sao Paulo (USP)](https://www5.usp.br/#english)</strong> <br/> gabrielshimanuki [at] usp [dot] br"
  # bio              : "Researcher in Electrical/Computer Engineering, specializing in machine learning and simulation for enhancing autonomous vehicle safety - <strong>[Safety Analysis Group (GAS)](https://www2.pcs.usp.br/~gas/) at <strong>[University of Sao Paulo (USP)](https://www5.usp.br/#english)</strong> <br/>"
  # bio              : "I am a Master’s student in Electrical and Computer Engineering at the [Polytechnic School](https://www-poli-usp-br.translate.goog/?_x_tr_sl=pt&_x_tr_tl=en&_x_tr_hl=pt-BR&_x_tr_pto=wapp) of the [University of São Paulo](https://www5.usp.br/english/institutional/), ranked as the leading university in Latin America ([#92 QS World University Ranking](https://www.topuniversities.com/world-university-rankings?page=3)). I conduct research within the Safety Analysis Group under the supervision of Prof. Paulo Sérgio Cugnasca and Dr. Alexandre Moreira Nascimento. My work focuses on enhancing the safety and optimization of autonomous systems, with the aim of creating reliable technologies capable of making safe decisions under uncertainty. My long-term goal is to accelerate the adoption of autonomous systems, including robotics and autonomous vehicles, and extend their societal benefits globally, particularly in developing regions. <br/> <br/> I obtained my B.Sc. in Computer Engineering from the [Polytechnic School](https://www-poli-usp-br.translate.goog/?_x_tr_sl=pt&_x_tr_tl=en&_x_tr_hl=pt-BR&_x_tr_pto=wapp) of the University of São Paulo, where I graduated among the top 10% of my class. During my undergraduate studies, I developed a robust safety investigation framework for autonomous vehicles, which led to award-winning projects recognized for advancing critical scenario generation and fault injection techniques. My current research builds on this foundation, integrating cutting-edge simulation tools such as CARLA and Scenic with hardware-in-the-loop (HIL) systems using platforms like Arduino and FPGA to bridge the gap between simulation and real-world applications. <br/> <br/> My research interests include Artificial Intelligence, Machine Learning, Robotics, and Simulation, with a focus on practical and scalable solutions. My projects have been supported by renowned institutions, including [CNPq](https://www-gov-br.translate.goog/mcti/pt-br?_x_tr_sl=pt&_x_tr_tl=en&_x_tr_hl=pt-BR&_x_tr_pto=wapp), [FDTE](https://www-fdte-org-br.translate.goog/?_x_tr_sl=pt&_x_tr_tl=en&_x_tr_hl=pt-BR&_x_tr_pto=wapp), and [Itaú-Unibanco (Data Science Center)](https://c2d-poli-usp-br.translate.goog/?_x_tr_sl=pt&_x_tr_tl=en&_x_tr_hl=pt-BR&_x_tr_pto=wapp). Through these efforts, I aim to contribute to the development of safe, accessible, and efficient autonomous technologies, inspired by a legacy of innovation and societal progress. My vision is to advance robotics and autonomous systems as transformative solutions, fostering collaboration and accessibility to address critical societal challenges."
  # bio              : "
  #   I am a Master’s student in Electrical and Computer Engineering at the [Polytechnic School](https://www-poli-usp-br.translate.goog/?_x_tr_sl=pt&_x_tr_tl=en&_x_tr_hl=pt-BR&_x_tr_pto=wapp) of the [University of São Paulo](https://www5.usp.br/english/institutional/), ranked as the leading university in Latin America ([#92 QS World University Ranking](https://www.topuniversities.com/world-university-rankings?page=3)). I conduct research within the Safety Analysis Group under the supervision of Prof. Paulo Sérgio Cugnasca and Dr. Alexandre Moreira Nascimento. My work focuses on enhancing the safety and optimization of autonomous systems, with the aim of creating reliable technologies capable of making safe decisions under uncertainty. My long-term goal is to accelerate the adoption of autonomous systems, including robotics and autonomous vehicles, and extend their societal benefits globally, particularly in developing regions. <br/> <br/>

  #   I obtained my B.Sc. in Computer Engineering from the [Polytechnic School](https://www-poli-usp-br.translate.goog/?_x_tr_sl=pt&_x_tr_tl=en&_x_tr_hl=pt-BR&_x_tr_pto=wapp) of the University of São Paulo, where I graduated among the top 10% of my class. During my undergraduate studies, I developed a robust safety investigation framework for autonomous vehicles, which led to award-winning projects recognized for advancing critical scenario generation and fault injection techniques. My current research builds on this foundation, integrating cutting-edge simulation tools such as CARLA and Scenic with hardware-in-the-loop (HIL) systems using platforms like Arduino and FPGA to bridge the gap between simulation and real-world applications. <br/> <br/>

  #   My research interests include Artificial Intelligence, Machine Learning, Robotics, and Simulation, with a focus on practical and scalable solutions. My projects have been supported by renowned institutions, including [CNPq](https://www-gov-br.translate.goog/mcti/pt-br?_x_tr_sl=pt&_x_tr_tl=en&_x_tr_hl=pt-BR&_x_tr_pto=wapp), [FDTE](https://www-fdte-org-br.translate.goog/?_x_tr_sl=pt&_x_tr_tl=en&_x_tr_hl=pt-BR&_x_tr_pto=wapp), and [Itaú-Unibanco (Data Science Center)](https://c2d-poli-usp-br.translate.goog/?_x_tr_sl=pt&_x_tr_tl=en&_x_tr_hl=pt-BR&_x_tr_pto=wapp). Through these efforts, I aim to contribute to the development of safe, accessible, and efficient autonomous technologies, inspired by a legacy of innovation and societal progress. My vision is to advance robotics and autonomous systems as transformative solutions, fostering collaboration and accessibility to address critical societal challenges."

  location         : "São Paulo, Brazil"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/gabriel-kenji/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/GabrielShimanuki"
    # - label: "Google Scholar"
    #   icon: "fas fa-fw fa-graduation-cap"
    #   url: "https://scholar.google.com/citations?user=B647vnMAAAAJ&hl=en"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-5412-8910"

# # Site Footer
# footer:
#   links:
#     - label: "LinkedIn"
#       icon: "fab fa-fw fa-linkedin-in"
#       url: "https://www.linkedin.com/in/gabriel-kenji/"
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/GabrielShimanuki"
#     # - label: "Google Scholar"
#     #   icon: "fas fa-fw fa-graduation-cap"
#     #   url: "https://scholar.google.com/citations?user=B647vnMAAAAJ&hl=en"
#     - label: "ORCID"
#       icon: "fab fa-fw fa-orcid"
#       url: "https://orcid.org/0000-0002-5412-8910"

# Reading Files
include:
  - .htaccess
  - _pages

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs 
  - /test
  - feed 

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

feed:
  path: false

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true
  #math_engine: mathjax
  syntax_highlighter: rouge

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: "America/Montreal"

# Plugins 
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
#- jekyll-feed
  - jekyll-include-cache
  #- jekyll-mathjax

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
#- jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: 
      share: true
      related: true

math: true

# mkdocs.yml
markdown_extensions:
  - tables
  - md_in_html

favicon: "/assets/images/website-icon-c-64.png"